RULES_CONFIG = {
    "LIGHT": {
        "font_check": True,
        "margins_check": True,
        "indent_check": True,
        "page_numbering": True,
        "title_page": True,
        "tables_basic": True,
        "images_basic": True,
    },
    "MEDIUM": {
        "font_check": True,
        "margins_check": True,
        "indent_check": True,
        "page_numbering": True,
        "title_page": True,
        "tables_basic": True,
        "images_basic": True,
        "structure_check": True,
        "headings_numbering": True,
        "toc_rebuild": True,
        "captions_full": True,
        "tables_full": True,
        "images_full": True,
        "bold_only_headings": True,
    },
    "HARD": {
        "font_check": True,
        "margins_check": True,
        "indent_check": True,
        "page_numbering": True,
        "title_page": True,
        "tables_basic": True,
        "images_basic": True,
        "structure_check": True,
        "headings_numbering": True,
        "toc_rebuild": True,
        "captions_full": True,
        "tables_full": True,
        "images_full": True,
        "bold_only_headings": True,
        "semantic_check": False,
        "formula_check": True,
        "bibliography_check": False,
        "abbreviations_check": True,
        "pdf_validation": True,
        "appendix_check": True,
    },
}


WEIGHTS = {
    "font_check": 1.5,
    "margins_check": 1.0,
    "indent_check": 0.8,
    "page_numbering": 0.8,
    "title_page": 0.7,
    "tables_basic": 0.7,
    "images_basic": 0.7,
    "structure_check": 1.5,
    "headings_numbering": 1.2,
    "toc_rebuild": 1.0,
    "captions_full": 1.0,
    "tables_full": 0.8,
    "images_full": 0.8,
    "bold_only_headings": 0.6,
    "formula_check": 1.0,
    "abbreviations_check": 0.8,
    "pdf_validation": 0.5,
    "appendix_check": 0.8,
}

